name: GitHub Classroom Workflow v2

on: [push]

env:
  DEVOPS_DIR: devops
  GHSECRET: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  grading:
    # autograding an assignment in GitHub Classroom
    # does not run for the first push by the classroom bot
    if: ${{ !contains(github.actor, 'classroom') }}
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # checkout the content of the repository
      - uses: marcel-suter-bzz/autograding@releases/v1
        # run the test cases in .github/classroom/autograding.json
        id: autograding
      - name: grade-moodle-assignment
        # grade the assignment in Moodle, runs even after an error in autograding
        if: always()
        run: |
          messages=${{ steps.autograding.outputs.Messages }}
          echo "Messages: $messages"
          grade=${{ steps.autograding.outputs.Points }}
          echo "Points: $grade"
          parts=(${grade//\// })
          points="points=${parts[0]}"
