name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  grading:
    if: ${{ !contains(github.actor, 'classroom') }}
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: education/autograding@v1
        id: autograding
      - name: export-grade
        if: always()
        run: |
          grade=${{ steps.autograding.outputs.Points }}
          parts=(${grade//\// })
          points="points=${parts[0]}"
          
          user="user_name=${{ github.actor }}"
          
          repofull=${{ github.repository }}
          parts=(${repofull//\// })
          reponame=${parts[1]}
          assignment="${reponame/"-${{ github.actor }}"/""}"

          wstoken="wstoken=f687ce33493a389d875c8c6c8288a7d6"
          wsfunction="wsfunction=local_gradeassignments_update_grade"
          assignment="assignment_name=$assignment"
          
          url="https://it.bzz.ch/demo/formdata/index.php?$wstoken&$wsfunction&$assignment&$user&$points"
          curl $url
