name: GitHub Classroom Workflow

on: [push]

env:
  DEVOPS_DIR: devops
  GHSECRET: ${{ secrets.GITHUB_TOKEN }}
  TARGET_REPO: ${{ github.repository }}
  SOURCE_REPO: BZZ-Commons/copy-issues
  SCRIPT_REPO: BZZ-Commons/copy-issues
  ADD_LABELS: "true"
  DATA_REPO: BZZ-Commons/set-testdata
  DATA_PATH: 'FIXME url'

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  grading:
    if: ${{ !contains(github.actor, 'classroom') }}
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: education/autograding@v1
        id: autograding
      - name: export-grade
        if: always()
        run: |
          grade=${{ steps.autograding.outputs.Points }}
          parts=$(echo $grade | tr "/" "\n")
          wstoken="wstoken=f687ce33493a389d875c8c6c8288a7d6"
          wsfunction="wsfunction=local_gradeassignments_update_grade"
          assignment="assignment_name=M293_LU07_A01_Book"
          user="user_name=${{ github.actor }}"
          points="points=$parts[0]"
          url="https://it.bzz.ch/demo/formdata/index.php?$wstoken&$wsfunction&$assignment&$user&$points"
          echo $url
          #curl -X POST "https://it.bzz.ch/fgitapi/gh_grade/${{ github.repository }}/${{ steps.autograding.outputs.Points }}"
